### ISSUE TITLE
unstable simulation quick fix

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a3#11]
Hi,

So I implemented almost all of the forces but one of them causes great unstability. Namely it is the alignment force, because it adds a force that is the average velocity of neighbouring birds, the velocity of every birds will accumulate over time and will overshoot, I followed the reference link in the homework.

I also tried to define the alignment force as the difference between the average velocity of neighbour to the velocity of one bird, but it does not work very well...

However by adding a simple force that is basically the negative of the current speed for each birds if it is above a certain magnitude, it makes the simulation much more stable. Is that allowed or should the simulation be stable without it?

**Comment by liyuesolo** [comment]
Hey,

I only meant to refer to the links for the images not for anything else which I didn't check myself. What do you mean doesn't work well? What did you observe, and can you analyze the reason? What's the reasoning behind adding a force as the negative speed, isn't this just a large damping? Basically, you define a force that penalizing the deviation of an objective. f = -d_objective/d_positon. In terms of debugging, I would recommend having minimal birds, define a large force and only run one time step to see if your state is closer to your objective, if not then figure out why. Besides, what do you mean by stable, it would be nice to provide detailed descriptions. Let's start with two birds with velocity vectors (1, 0), (0, 1), and you add a force to one of them to drag it towards the average. You run one time step, v += dt * f, x+=dt*v and see what velocity you end up with, if tit's not the average, then debug it.

Hopefully, this can be helpful.
Yue
