### ISSUE TITLE
Task 3 Alignment

### ISSUE THREAD

**Issue by iqiac** [cmm-21/a3#12]
Hello

I'm stuck at implementing the force vector for alignment in task 3. I'm not sure if I understood something wrong conceptual. I tried the standard implementation one can find anywhere in the internet, i.e. adding the average velocitiy of the neighbors. I also tried with damping and including average position of neighbors, but the boids seem to scatter too much and somehow it seems the initial (random) velocity is dominant. This can be seen here: https://youtu.be/iTmo4ByxXkY.

I'll push my code now. The main issue should be in getAlignVec() in boids.h. I hope you can see what's wrong or give some intuition how this could be corrected.

Thanks in advance.

**Comment by liyuesolo** [comment]
Hi 

I've checked your code. Yes, you did understand things wrong conceptually, I think it originates from these "standard implementations". I only meant to refer to the links for their images. You should figure it out yourself, but maybe get rid of those implementations first and start asking yourself, what is a force and what does it do?  What is your objective in your implementation, does your force penalize the deviation?

Yue

**Comment by iqiac** [comment]
Okay thanks, it seems to work better now.
