### ISSUE TITLE
Modify TVStack size

### ISSUE THREAD

**Issue by Glanfaloth** [cmm-21/a3#14]
Hi! May I ask how to append a column in TVStack? (for creating new birds)

In boid.cpp, case 7 of updateBehavior I tried resize() and conservativeResize() but there was always this error: `Assertion failed: ((i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))), function Block, ../build/_deps/eigen-src/Eigen/src/Core/Block.h, line 122.`

**Comment by liyuesolo** [comment]
Hi

I just wrote an example code, hopefully, it would be informative. 

![image](https://user-images.githubusercontent.com/15157399/114448852-5d8fa880-9bd4-11eb-997f-b41c3569eae9.png)

command line output
![image](https://user-images.githubusercontent.com/15157399/114448926-7435ff80-9bd4-11eb-804e-28217f8211b5.png)


raw code

void TVStackTVTutorial()
    {
        TVStack a_great_TVStack(dim, 5);
        for (int i = 0; i < 5; i++)
            a_great_TVStack.col(i) = i * TV::Ones();
        std::cout << a_great_TVStack << std::endl;
        // you can also std::cout << a_great_TVStack.transpose() << std::endl;
        
        // oh I don't want col 3 now
        // emm, it's a Stack! it must be named for a reason 
        // let's move it to the end and pop it!

        // here we move the 5th col to the 3rd column
        a_great_TVStack.col(3) = a_great_TVStack.col(4);
        std::cout << a_great_TVStack << std::endl;

        // we fake the pop stack operation by conservativeResize()
        a_great_TVStack.conservativeResize(dim, 4);
        std::cout << a_great_TVStack << std::endl;

        // now I want to push vectors to the stack
        // let's grab another TVStack
        TVStack yet_another_TVStack(dim, 6);
        for (int i = 0; i < 6; i++)
            yet_another_TVStack.col(i) = (i + 5) * TV::Ones();
        std::cout << yet_another_TVStack << std::endl;

        // make room for the newbee
        a_great_TVStack.conservativeResize(dim, 4 + 6);
        // here is a block assignment, .template block is equivalent to block
        // here dim is a template variable hence template block
        a_great_TVStack.template block<dim, 6>(0, 4) = yet_another_TVStack;
        std::cout << a_great_TVStack << std::endl;
    }
