### ISSUE TITLE
Alignment (Ex.3)

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a3#16]
Dear TAs
Quick Question:
In Ex3, when we need to implement the alignment behaviour, the exercise says 
"In addition to moving toward the average position of neighboring birds, ..."

Just to be clear, in the demonstration of the alignment part, you want to have adhesion AND alignment? Or do we have to show each of them individually?
(and for the third part alignment, adhesion and separation and so on)

Thank you in advance

**Comment by liyuesolo** [comment]
Hi,

We would like you to show them individually.

Yue
