### ISSUE TITLE
Cursor Position

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a3#17]
Dear TAs
I have a question regarding the imgui.h you are using. I am currently struggling to get the position of the cursor in the window. I tried ImGui::GetCursorPos(), but this leads to a crash. What do you recommend to get the cursor position?

Best,
Manuel

**Comment by nwicki** [comment]
Try ImGui::GetMousePos(). I had some strange offset - adding 25 to the y coordinate helped.

**Comment by TunVunDerBunn** [comment]
you can also have a look at the MouseState class in the application.h

**Comment by liyuesolo** [comment]
Hi,

The usage is identical to assignment 0. Feel free to fetch the codes there.

**Comment by liyuesolo** [comment]
@nwicki might be that you didn't reverse the shift_to_01 process.

**Comment by Maenzgi** [comment]
Thank you all!
