### ISSUE TITLE
Question about collision avoidance

### ISSUE THREAD

**Issue by luohwu** [cmm-21/a3#18]
Hi Yue,

Currently, my implementation pushes birds away when they hit the obstacle or are close to the obstacle. Is this enough to get the points? I am not sure that my understanding of  "steer around a given obstacle" is correct or not.

In addition, while implementing collision avoidance, do I need include previous tasks such as cohesion and separation?

**Comment by liyuesolo** [comment]
Hi,

Yeah push away when they hit the obstacle is fine, you don't have to include previous tasks.

**Comment by luohwu** [comment]
I see. Thank you!
