### ISSUE TITLE
Spawning a collision object vs. Window scaling

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a3#19]
Dear TAs

Quick question: I noticed that in your provided code, if you change the size of the window (say you run it in full screen), both x and y coordinates are scaled with it. This is not a problem at all, except for the collision exercise. The problem is, that if I draw a circle, it stays a a circle, no matter how I scale the window. I wanted to have a circle with a given radius and implement the collision avoidance, and then draw the circle to visualize its size. However, this doesn't work when the window is scaled.
My question: Is it fine if the collision only works if the window is not being resized, or is there a way to draw the circle to respect the size of the window? (It should be elliptic after scaling). 

Best,
Manuel

**Comment by liyuesolo** [comment]
It's ok to work for a fixed size.

**Comment by Maenzgi** [comment]
Thank you for the fast response! I will implement it for a fixed size then.
