### ISSUE TITLE
Collaborative and Adversarial Behaviors - What should Boids do?

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a3#20]
Dear TA

Just to be clear: In the first part off the last Exercise you say:  _"Using the symplectic Euler method with random initial positions and velocities, observe the evolution of the populationsand concisely report your findings in the ReadMe file"_

Do the boids in this scenario also have flocking behaviour? Or do you want us just to check what happens if the have random velocities? If Flocking occurs: Does it happen among all boids, or just the ones that are from the same "groups"?

Best,
Manuel

**Comment by liyuesolo** [comment]
No, here you are not required to include flocking behaviors.

**Comment by Maenzgi** [comment]
Ok thank you.
But now I already did, is this ok? Otherwise they don't move at all.

**Comment by liyuesolo** [comment]
it is ok but I don't understand if you have random velocities how could they not move.
