### ISSUE TITLE
Freezing of the app - Collaborative and Adversarial Behavior

### ISSUE THREAD

**Issue by TunVunDerBunn** [cmm-21/a3#21]
Dear TA's,

Depending on how the birds are initialized (positions and velocities), the number of birds grows quite quickly. My implementation seems to be quite inefficient, because the app freezes completely if around 150 birds are generated in total. Should I try to optimize my implementation or is it not a big issue as long as it can be seen, that the algorithm works fine in the first few instants.

Thank you very much already in advance.

**Comment by liyuesolo** [comment]
Hi, 

Please check if you have unnecessary for loops, otherwise, try to figure out why they grow so fast. You might have to adapt your implementation on a high level. The grading will be sure based on what you already had even if they are not perfect.

Best of luck!
Yue

**Comment by TunVunDerBunn** [comment]
Okay, I will go a bit through my code and see what I can do.

Thank you very much for the quick rely.
