### ISSUE TITLE
Collaborative and Adversarial Behaviors : boids

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a3#22]
Dear TA team,

By boids you mean particles right? or group of particles?

Thank you

**Comment by liyuesolo** [comment]
Not sure in what case it makes a difference, do you mean whether you need flocking behaviors for the last task or what?

**Comment by lthiet** [comment]
so if boids were group of particles i would think that two large group would make a new group of particle by following a new leader? but if three boids from one "team" is close to one boids from another team, then the latter's leader would lose its status as leader and perhaps the boids is dispatched? but then i'm not sure what is mean by tracking population...

so probably when 2 particles are close to each other another one in the middle is created right? is this what was meant?

**Comment by liyuesolo** [comment]
when 2 particles are close to each other another one in the middle is created, yes, but you might have to add a pseudo time stamp such that they don't generate a new one immediately again. Or assign parent-child structure to it or some other strategies you come up with!

**Comment by lthiet** [comment]
i see, thanks!
