### ISSUE TITLE
Symplectic Euler with velocity-dependent force?

### ISSUE THREAD

**Issue by lnumerow-ethz** [cmm-21/a3#23]
Symplectic Euler is defined assuming position dependent force f(x), but what should the update look like for a force that depends also on velocity f(x, v), such as in circular motion?

Should we implement:
a) v<sub>n+1</sub> = v<sub>n</sub> + h * f(x<sub>n+1</sub>,v<sub>n</sub>)

or something like this?
b) v<sub>n+1</sub> = v<sub>n</sub> + h * f(x<sub>n+1</sub>, v<sub>n</sub> + h * f(x<sub>n</sub>, v<sub>n</sub>))

**Comment by liyuesolo** [comment]
For the circular motion, you don't need a velocity-depended force.

**Comment by lnumerow-ethz** [comment]
The question applies also to other forces (alignment, damping).

Thanks for the clarification about the circular motion though - I had the wrong idea. :)

**Comment by liyuesolo** [comment]
It's ok to use explicit Euler for the flocking behaviors. Per your question, vn+1 = vn + h * f(xn+1,vn) is fine.

**Comment by lnumerow-ethz** [comment]
Thanks!
