### ISSUE TITLE
debugging in vs code stuck

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a3#5]
hi,

when debugging like we've done similarly for previous project in vs code, the debugger seems to be stuck before the window of the app open. maybe it was explained during the zoom exercise? if it is so could you pinpoint me to the timestamp at which this was explained?

many thanks

**Comment by liyuesolo** [comment]
Hi,

I'll try to figure it out and get back to you. In the meanwhile, can you try to print values that you want to check? vector size, entry of an array, or sth? Whatever you can check in your debugger you can print it out.

**Comment by eastskykang** [comment]
Could you elaborate it more? What does exactly means "stuck"? and please try to identify where it stuck.

**Comment by lthiet** [comment]
@liyuesolo yes it is still possible to print but much harder to keep track of how these values change over time

@eastskykang i press the bug button on the control bar at the bottom as it was explained in the tutorial session. now the debugger is stuck at this point, i'm not too sure what kind of state that is 

![Screenshot from 2021-04-07 15-08-44](https://user-images.githubusercontent.com/26815719/113871408-29bb1a00-97b3-11eb-82c5-fda100d1b4e8.png)

i cannot get to the next breakpoint in the picture (the line that says `int width = 720;`, which should be the first line that is run right? the ide still works, i just can't run the code along with the debugger.

**Comment by lthiet** [comment]
so the problem was which compiler i used, i was using `clang` but with `gcc` it worked. not sure why but it works now.

**Comment by eastskykang** [comment]
@lthiet as far as I remember, if you use clang in Linux, you need an additional setting for clang debugger. Thank you for your reporting.
