### ISSUE TITLE
Mass Matrix / Integrator Methods and Part 3

### ISSUE THREAD

**Issue by Maenzgi** [cmm-21/a3#6]
Dear TAs

I am about the set up the code and I need to know two things in advance:
-Do we ever have to assign individual weights to the birds? Otherwise, it doesn't make much sense to define a Mass matrix in my opinion, a scalar would do the job.
-Do we have to implement the integrators in a way that they work for all behaviours in Part 3 of the exercise, or just for the demonstration in Part 2? (Meaning: Can we always use Explicit Euler for part 3)? I am asking this because I think if I want all integrators to work, it might be that I have to change some of the structure of the given code.

Best and thank you in advance
Manuel

**Comment by liyuesolo** [comment]
Hi Manuel,

You can assume constant mass for all birds, the mass matrix in the equation is just a general formulation. 

You can change the structure of the given code in any way that is convenient for you and you can use Explicit Euler for flocking behaviors.

Best,
Yue

**Comment by liyuesolo** [comment]
@Maenzgi Can I close this issue or is there anything unclear?
