### ISSUE TITLE
Position of origin

### ISSUE THREAD

**Issue by PanagiotisAnagnostaras** [cmm-21/a3#7]
Hello everyone! I am trying to find how to move the origin in relation with the application window without luck. Can anyone provide a hint?

**Comment by liyuesolo** [comment]
Hi, 

I wrote a shift_01_to_screen function to shift the simulation domain to the screen space. You can modify it in any way you feel convenient. You can always draw (0, 0). (0.5, 0.5)..... to the screen to figure out the relative position. It is just a linear mapping after all. To answer your specific question, draw only (0, 0) and you will see it on screen.

**Comment by liyuesolo** [comment]
@PanagiotisAnagnostaras May I close this issue or is there anything unclear?

**Comment by PanagiotisAnagnostaras** [comment]
Yes it is clear, Thanks!
