### ISSUE TITLE
Leader bird

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a3#8]
just a quick question, should the leader also be considered a bird, i.e. subject to the same forces as the others birds with the exception the forces corresponding to following the leader?

**Comment by liyuesolo** [comment]
For my implementation, the repulsive force holds the same, the dragging force corresponds to my cursor position.

**Comment by lthiet** [comment]
so basically every birds has another force that directs it towards the mouse position?

**Comment by liyuesolo** [comment]
The leader is dragged by a force that corresponds to the cursor position, all the others try to approach the leader and head in the same direction (without direct impact from the cursor location) meanwhile maintaining sufficient distance. Is this clear?

**Comment by lthiet** [comment]
okay that makes sense, thank you

**Comment by liyuesolo** [comment]
sure no problem
