### ISSUE TITLE
"Overshoot" Cohesion

### ISSUE THREAD

**Issue by benjirer** [cmm-21/a3#9]
Hi! While implementing the cohesion behaviour I am running into a small problem. My birds flock together at first, as is the plan, however they never really converge. After reaching a common point, they "overshoot" the target and keep wizzing around the "common point", just in a smaller radius as before. I've tried adapting the stepsize, as well as scaling my applied forces but all it does is slow down the process. Maybe somebody has a hint as to where my problem is? (Maybe my numerical schemes are wrong?) Thank you!

**Comment by liyuesolo** [comment]
Can you push your code so I can have a look? The description is a bit sketchy. Or instead of flying towards the moving average, can you add a giant force to drag all birds to move to a specific target, say, (0.5, 0.5) for example, and see if it works (all aggregate to that point)?

**Comment by benjirer** [comment]
Hi Yue, sure I just pushed it. Aggregating towards one point has the same issue.

**Comment by liyuesolo** [comment]
Hi, I think I should let you figure out the reason yourself actually but in your implementation, you could add some damping forces f_damp = k * velocity. Or think of other penalization forces.

Some minor issue regarding your code,  Matrix<float, 2, 40> this is just TVStack(dim, n). all your float is basically T, that's the whole point of using a template.

**Comment by benjirer** [comment]
Certainly, thank you! 

Ah yes, thanks for pointing that out, I will change that.
